language: node_js
node_js:
  - "0.12"
cache:
  directories:
      - node_modules
services:
  - postgres
before_script:
  - psql -c 'create database historyoftest;' -U postgres
env:
  - POSTGRESQL_ADDON_HOST=localhost POSTGRESQL_ADDON_USER="" POSTGRESQL_ADDON_PASSWORD="" POSTGRESQL_ADDON_DB=historyoftest
