language: node_js
node_js:
  - "6"
cache:
  directories:
      - node_modules
services:
  - postgresql
install:
  - psql -c 'create database historyoftest;' -U postgres
  - npm install
env:
  - POSTGRESQL_ADDON_HOST=localhost POSTGRESQL_ADDON_USER="" POSTGRESQL_ADDON_PASSWORD="" POSTGRESQL_ADDON_DB=historyoftest
